# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano
#     shield: reviung41
#
---
include:
  # # Urchin https://github.com/duckyb/zmk-urchin
  # - board: nice_nano
  #   shield: urchin_left nice_view_adapter nice_view
  # - board: nice_nano
  #   shield: urchin_right nice_view_adapter nice_view
  #
  # # Brain https://github.com/Wesztman/brain
  # - board: nice_nano
  #   shield: brain_left nice_view_adapter nice_view
  # - board: nice_nano
  #   shield: brain_right nice_view_adapter nice_view

  # Lily58 https://github.com/kata0510/Lily58
  - board: nice_nano
    shield: splitkb_aurora_lily58_left
  - board: nice_nano
    shield: splitkb_aurora_lily58_right

  # # Reset
  # - board: nice_nano
  #   shield: settings_reset

  # - board: nice_nano
  #   shield: tester_pro_micro
